use_frameworks!

platform :ios, '11.0'

target 'WPGameSDK_Example' do
  
  pod 'WPGameSDK', :git => 'https://github.com/trc19930224/WPGameSDK.git'
#  pod 'WPGameSDK', :path => '../'
  pod 'LookinServer'
  pod 'Bagel'

  target 'WPGameSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end
